### ISSUE TITLE
Add apischema author as maintainer

### ISSUE THREAD

**Issue by klauer** [conda-forge/apischema-feedstock#1]
@wyfo:

First of all, thank you for apischema - it's a truly great library.

I just made this conda-forge feedstock for apischema in order to better integrate with my facility's packaging requirements (conda-everything; PyPI is secondary).

I am currently the only maintainer of this newly-created feedstock. I'd like to offer you the choice of the following options moving forward:
1. Add you as a maintainer in addition to myself
2. Remove myself as a maintainer, add you as the sole maintainer
3. Continue maintaining the feedstock myself

Feel free to let me know your preference and I'll happily oblige.

**Comment by wyfo** [comment]
Thank you a lot for this feedback, and for this initiative.

Actually, I've to admit I don't know the Conda ecosystem at all, so I'm not the best person to maintain this feedstock. But I'm still willing to get involved in it, and I'm happy that you propose me doing so, so I'd like to go along with the first option.

**Comment by klauer** [comment]
No problem at all. 

Great! I'll add you, then (#3).
