### ISSUE TITLE
Examples dependencies can lead to dependencies conflict

### ISSUE THREAD

**Issue by wyfo** [conda-forge/apischema-feedstock#2]
Example dependencies are present in *Pypi* package as an extra requirement in order to quickly execute the examples code of the documentation.

However they are not required at all by *apischema* to work. Having a version constraint on them in the feedstock could lead to dependencies conflict if a user install *apischema* while already having one of these package installed with a lower version that currently "required" by the feedstock.

Because they are not real dependencies, I would suggest to simply remove them.

**Comment by klauer** [comment]
That is a fair point, and one that I tried to weigh the alternatives of when submitting the feedstock:

On one hand, the apischema examples would (or at least _may_) not work if API-incompatible versions of those packages are installed.
On the other hand, installations of apischema are of course not limited to those just poking around with the examples.

I'm perfectly fine with removing them for now, and will submit a PR shortly.
