### ISSUE TITLE
Bump version 0.15.5

### ISSUE THREAD

**Issue by wyfo** [conda-forge/apischema-feedstock#5]
Patch version 0.15.5 has been released, feedstock should be updated.

@klauer As I had not the time yet to get familiar with Conda, could you please do the upgrade? I will see look at it to be able to reproduce it next time. 

By the way, we didn't decide on a process for version upgrade. For example, should the upgrade PR be approved by both maintainers ? 

*apischema* is my first open-source project, so I'm still learning about how to manage it.

**Comment by klauer** [comment]
@wyfo, great!

Usually, the conda bot (@regro-cf-autotick-bot) will notice the new release on GitHub within a certain amount of time and automatically open a pull request with the bumped version, fixed hash, and so on. (see [here](https://github.com/pulls?utf8=%E2%9C%93&q=is%3Aopen+is%3Apr+author%3Aregro-cf-autotick-bot+archived%3Afalse+) for all the bot's PRs as a point of interest)

When the above works - and works within an acceptable period of time - it's a really great and convenient system. 

I'm happy to do the version bump manually, but perhaps we should wait and see if the bot will pick it up (if you're not in a hurry).

As to whether we should both approve it, that's certainly up to us. There's a certain level of trust, as either of us can merge PRs without the other's approval. At least for the first few releases, how about we both approve and then merge? Once you're more comfortable with how conda-forge works, then (as this is your package) merging without requiring my approval seems appropriate.

**Comment by wyfo** [comment]
It's true I'm kind in a hurry when it comes to patches — I try to fix bugs in less than 24h — but Conda release is not urgent if no user ask for it. And I'm happy to see the bot in action.

> As to whether we should both approve it, that's certainly up to us. There's a certain level of trust, as either of us can merge PRs without the other's approval. At least for the first few releases, how about we both approve and then merge? Once you're more comfortable with how conda-forge works, then (as this is your package) merging without requiring my approval seems appropriate.

Ok for me 👍
